### PR TITLE
Add models and websocket communication

### PR DESCRIPTION
**Pull request by yusuf-musleh**
There is a lot going on in this PR, I think it is really important to take the time to get model design right from the beginning otherwise we are gonna face some disgusting problems in the future.

Django has this thing called [ContentType](https://docs.djangoproject.com/en/1.11/ref/contrib/contenttypes/), this allows you to have a model with a ForeignKey to any of your models dynamically. So I used that for the `Token` model.

Essentially a `Token` can have a ForeignKey to either `Hub`, `Hotel`, `Room` models. This makes it easy to figure out who the token belongs to when we get websocket connects, and determine who to send the information to. This is extremely extendable, incase we want to change anything or add more entities that can communicate through sockets.

Websocket url looks like this: `api.local.com/stream/[TOKEN]`. Where `TOKEN` is a uuid, for example something like this: `b2531327-3b8d-4b3e-9418-c23d9907fb70`

The logic for determining the websocket group, and sending the information is defined in each model according. Keeping related code together, allows more clean and modular code.

I added a `User` model that extends django's builtin `AbstractUser` and used it as the default user for django. Essentially this does nothing, because we are not extending or adding anything new, but doing this at the beginning will make it so much easier to add `HotelUser`, `HubUser`, `RoomUser` models by extending our `User` model, while maintaining django's default user functionality, such as permissions/authentication, without going through hoops to make it work mid-project. Recommended in the django [docs](https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#substituting-a-custom-user-model).

### CODE REVIEW

**Review by mfituri — APPROVED** [review]
Code wajid zain. Good job 👍.

**Comment by Hasan-Jawaheri** [comment]
Looks good, some comments:

- Why do we have floors? seems useless (e.g. a separation by room type (# bedrooms, suite, etc..) would be slightly more useful, but neither seems actually helpful). Even if we want to add the separation at some point for whatever reason it seems better to put it as a field in the room's model, no?

- Why are you using the tokens as the group names? wouldn't the ID of the hotel/room/hub objects make more sense? so if you have multiple tokens per hotel it doesn't matter

rest seems very clean, noice

**Comment by Hasan-Jawaheri** [comment]
Also, please address rooms by their **name** not number. So messages **from the hub** will have a field "__room_names" which is an array of strings, each one is a room name associated with the message (yes you can get a message that "comes from multiple rooms", ill explain later). Any message **sent to the hub** must have one single "__room_name" field attached in it which tells the hub which room it should dispatch the message to.

**Comment by yusuf-musleh** [comment]
I added the following logic flow of the messages:
- For all messages **coming** from the hub: 
-- If the `__room_names` string list field not provided, don't do anything
-- If the `__room_names` string list field is provided forward message to hotel dashboard as is, with the list. Since the dashboard can know what needs to be updated, it needs that information.
-- Also loop through all the rooms in the list, check if they are valid rooms in the hotel and forward the message to them **without** the `__room_names` field in the message
- For all message **going** to hub:
-- I add a `__room_name` string field to the message that contains room name if coming from room, or `"[HOTEL_NAME] dashboard"` if coming from dashboard (this can be changed as needed).

**Review by mfituri — APPROVED** [review]
Code wajid zain ^2.

**Pull request merged**
